config/routes.rb
Rails.application.routes.draw do

  resources :faqs, only: [:create]


  # Home Controller HTTP VERB Routes
  get('/', {to: 'home#index', as: :root})
  get('/faq', {to: 'home#faq'})

  # About Controller HTTP VERB Routes
  get('/about', {to: 'about#index'})

  # Questions Controller HTTP VERB Routes
  delete('/questions/:id', {to: 'questions#destory'})
  get('/questions/:id/edit', {to: 'questions#edit'})
  get('/questions/:id', {to: 'questions#show'})

  # Comments Controller HTTP VERB Routes
  post('/questions/:id/comments', {to: 'comments#create'})

  #  Contact Controller HTTP VERBS Routes
  get('/contact', {to: 'contact#index'})

  post('/contact', {to: 'contact#submit'})

  # # Products Controller HTTP VERBS Routes
  #
  # # Products#new
  # get('products/new', to: 'products#new', as: :new_product)
  #
  # # Products#create
  # post('products', to: 'products#create', as: :products)
  #
  # # Products#show
  # get('products/:id', to: 'products#show', as: :product)
  #
  # # Product#index
  # get('products', to: 'products#index')
  #
  # # Product#destroy
  # delete('products/:id', to: 'products#destroy')
  #
  # # Product#edit
  # get('products/:id/edit', to: 'products#edit', as: :edit_product)
  #
  # # Product#update
  # patch('products/:id', to: 'products#update')

  resources :products, shallow: true do
    resources :reviews, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]
  end

  resources :reviews, only: [], shallow: true do
    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end

  patch('review/hide/:id', to: 'reviews#hide', as: :hide_review)

  resources :users, only: [:new, :create, :show] do
    resources :favourites, only: [:index], shallow: true
  end

  resource :session, only: [:new, :create, :destroy]

  namespace :admin do
    resources :panel, only: [:index]
  end

  resources :news_articles

  resources :tags, only: [:index, :show]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products, only: [:index, :show, :create]
      resources :users, only: [:create]
      resources :tokens, only: [:create, :destroy]
    end

    match "*unmatched_route", to: "application#not_found", via: :all
  end

  match "delayed_job", to: DelayedJobWeb, anchor: false, via: [:get, :post]


end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy

  # MtM Association with Users: Favourites
  has_many :favourites, dependent: :destroy
  has_many :users, through: :favourites

  # MtM Association with Tags: Taggings
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  # FAQs
  has_many :faqs, dependent: :destroy
  accepts_nested_attributes_for :faqs, reject_if: :all_blank, allow_destroy: true

  # Validations
  after_initialize :default_zero_hit
  before_validation :set_default_price
  before_validation :set_default_sale_price

  validates :title,
    presence: true,
    uniqueness: {case_sensitive: false},
    format: {without: /Apple|Microsoft|Sony/i}

  validates :price, numericality: {greater_than: 0, less_than: 1000}
  validates :description, presence: true, length: {minimum: 10}
  validates :sale_price, numericality: {less_than_or_equal_to: :price}

  before_save :capitalize_title
  # before_destroy :notify_delete


  # Helpful Methods
  def self.search(search_word)
    Product.where('title ILIKE ? OR description ILIKE ?', "%#{search_word}%", "%#{search_word}%")
  end

  def self.search_(search_word)
    Product.where('title ILIKE ?', "%#{search_word}%") + Product.where('description ILIKE ?', "%#{search_word}%")
  end

  def increment
    self.hit_count += 1
  end

  def self.filter(search_term, sort_by_column, current_page, per_page_count)
    Product
      .where( 'title ILIKE ? or description ILIKE ?', "%#{search_term}%", "%#{search_term}%" )
      .order( "#{sort_by_column}": 'ASC' )
      .limit( per_page_count )
      .offset( ( current_page - 1 ) * per_page_count )
  end

  include FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  mount_uploader :image, ImageUploader

  private

  def set_default_price
    self.price ||= 1
  end

  def capitalize_title
    self.title.capitalize!
  end

  def set_default_sale_price
    self.sale_price ||= self.price
    self.sale_price = self.price if self.sale_price > self.price
  end

  def default_zero_hit
    self.hit_count = 0
  end

  def notify_delete
    puts 'Product is about to be deleted'
  end

end


# Product.where('price > 20 and price < 70').order(title: "ASC").limit(10)

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    render json: Product.order(created_at: :desc)
  end

  def show
    render json:(Product.find params[:id])
  end

  def create
    product = Product.new(params.require(:product).permit(:title, :description, :price, :sale_price))
    product.user = current_user
    product.save!

    render json: product
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_product, except: [:new, :create, :index]
  before_action :authorize_user!, only:  [:edit, :update, :destroy]

  def new
    @product = Product.new
    @product.faqs.build
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user

    if @product.save
      CreateProductMailer.notify_product_owner(@product).deliver_now
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @review = Review.new
    @reviews = @product.reviews.sort_by { |review| -1 * review.vote_total }

    @favourite = @product.favourites.find_by(user_id: current_user) if current_user.present?
  end

  def index
    @products = Product.order(updated_at: :desc)
  end

  def destroy
    @product.destroy

    redirect_to products_path
  end

  def edit
  end

  def update
    if @product.sale_price > @product.price
      temp_sale = @product.sale_price
      @product.sale_price = @product.price
    end

    if @product.update product_params
      redirect_to product_path(@product)
    else
      @product.sale_price = temp_sale
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :image, {faqs_attributes: [:id, :question, :answer], tag_ids: []}
    )
  end

  def find_product
    @product = Product.find params[:id]
  end

  def authorize_user!
    unless can?(:crud, @product)
      flash[:alert] = 'Access denied'
      redirect_to product_path(@product)
    end
  end


end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_faq_fields.html.erb
<div class="nested-fields">
  <%= f.input :question %>
  <%= f.input :answer %>
  <%= link_to_remove_association "remove FAQ", f %>
</div>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :image %>
  <%= f.association :tags, input_html: { class: 'chosen-select' } %>
  <%= f.simple_fields_for :faqs do |op| %>
    <%= render 'faq_fields', f: op %>
  <% end %>
  <div class="links">
    <%= link_to_add_association 'add faq', f, :faqs %>
  </div>

  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product Page</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>Products Page</h1>
<% @products.each do |product| %>
  <div>
    <%= link_to product.title, product_path(product) %> Price: <%= number_to_currency(product.price) %>
  </div>
<% end %>

app/views/products/new.html.erb
<h1>New Product </h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>

<div class="tag-containers">
  <% @product.tags.order(:name).each do |tag| %>
    <%= link_to tag.name, tag_path(tag), class: "badge badge-pill badge-primary" %>
  <% end %>
</div>
<p>Product Description: <br/><%= @product.description %></p>
<p>Product Price: <br/><%= number_to_currency(@product.price) %></p>

<%= image_tag @product.image.url(:medium) if @product.image.present? %>

<div>
  <small>
    Created
    <%= time_ago_in_words(@product.created_at) %>
    ago
  </small>
  •
  <small>
    Page last edited
    <%= time_ago_in_words(@product.updated_at) %>
    ago
  </small>
  <small>by <strong><%= "#{@product.user.first_name} #{@product.user.last_name}" %></strong></small>
</div>

<div>
  <% if can?(:crud, @product) %>
  <%= link_to 'Update', edit_product_path(@product)%>
  <%= link_to 'Delete', product_path(@product),
    method: :delete,
    data: {
      confirm: 'Are you sure?'
    }
   %>
   <% end %>
</div>
<% if @favourite.present? %>
  <%= link_to fa_icon('heart 2x'), favourite_path(@favourite), method: :delete %>
<% else %>
  <%= link_to fa_icon('heart-o 2x'), product_favourites_path(@product), method: :post %>
<% end %>

<div class="faqs-container">
  <h3>Frequently Asked Questions</h3>
  <% @product.faqs.each do |faq| %>
    <p><strong> Question: <%= faq.question %> </strong></p>
    <p> Answer: <%= faq.answer %> </p>
  <% end %>
</div>

<%= simple_form_for [@product, @review] do |f| %>

<h2>Add Review </h2>
<%= f.input(:rating, in: 1..5, step: 1, placeholder: '') %>
<%= f.input :body %>
<%= f.submit "Send Review" %>
<% end %>

<h2>Reviews</h2><hr>
<% @reviews.each do |review| %>

  <% if review.hidden %>
    <% if can?(:crud, @product) %>
      <div class="review-list-item semi-hidden">
    <% else %>
      <div class="review-list-item hidden">
    <% end %>
  <% else %>
      <div class="review-list-item">
  <% end %>

        <p>Rating: <%= review.rating %>/5
          <small><%= link_to "Toggle Hide", hide_review_path(review), method: :patch %></small>
          <% if can?(:destroy, review) %>
            <small><%= link_to "Delete", review_path(review), method: :delete %></small>
          <% end %>
        </p>
        <p><%= review.body %></p>
        <small>Review made <%= time_ago_in_words(review.created_at) %> ago</small>
        <small> by <%= "#{review.user.first_name} #{review.user.last_name}" %> </small>
        <br>

        <div class="like-spot">
          <% like = review.likes.find_by(user: current_user) %>
          <% if like.present? %>
            <%= link_to fa_icon('check-circle'), like_path(like), method: :delete %>
          <% else %>
            <%= link_to fa_icon('circle-o'), review_likes_path(review), method: :post %>
          <% end %>
          <span><%= pluralize(review.likes.count, 'user') %> liked this</span>
        </div>

        <div class="vote-spot">
          <% vote = review.votes.find_by(user:current_user) %>
          <% if vote.nil? %>
            <%= link_to fa_icon('arrow-circle-o-up 2x'), review_votes_path(review, {choice: true}), method: :post %>
            <%= review.vote_total %>
            <%= link_to fa_icon('arrow-circle-o-down 2x'), review_votes_path(review, {choice: false}), method: :post %>
          <% elsif vote.choice? %>
            <%= link_to fa_icon('arrow-circle-up 2x'), vote_path(vote), method: :delete %>
            <%= review.vote_total %>
            <%= link_to fa_icon('arrow-circle-o-down 2x'), vote_path(vote, {choice: false}), method: :patch %>
          <% else %>
            <%= link_to fa_icon('arrow-circle-o-up 2x'), vote_path(vote, {choice: true}), method: :patch %>
            <%= review.vote_total %>
            <%= link_to fa_icon('arrow-circle-down 2x'), vote_path(vote), method: :delete %>
          <% end %>

        </div>

        <hr>
      </div>

<% end %>